[book]
authors = ["Carmine Spagnuolo"]
language = "en"
multilingual = false
src = "src"
title = "Programmazione Concorrente, Parallela e su Cloud (PCPC) @ UNISA"
description = "materiale di supporto al corso di PCPC"
